export type SeedCustomer = { name: string; mobile?: string; gst?: string };

export const SEED_CUSTOMERS: SeedCustomer[] = [
  { name: "SHREE GAJANAN SWEETS", gst: "27GYZPR4027K1ZE" },
  { name: "Jha's Sweets & Dryfruit", mobile: "9869718755", gst: "27CDTPJ7718J1ZT" },
  { name: "VAISHALI ENTERPRISES Hitesh", gst: "27AFHPJ9544G1Z6" },
  { name: "Raksha Hospitality Pvt Ltd", mobile: "9833999055" },
  { name: "SILENT HILLS RESORT LIMITED", gst: "27AACCS0342J1ZI" },
  { name: "Patel Brothers", mobile: "7021158625", gst: "27AKLPP3232G1Z4" },
  { name: "VEG TREAT HOTELS PRIVATE LIMITED", gst: "27AADCV4687N2ZH" },
  { name: "THE VEG TREAT IV", gst: "27AAQFT7358E1ZM" },
  { name: "THE VEG TREAT UDUPI", gst: "27AAXFT4970H1ZD" },
  { name: "THE GLOBAL VEG TREAT", gst: "27AAXFT4969J1Z1" },
  { name: "THE VEG TREAT LEGACY", gst: "27AASFT6189P1ZU" },
  { name: "THE VILLA EXOTIC SIP & CUISINE", gst: "27AAUFT3153F1ZV" },
  { name: "THE VEG TREAT CELEBRATION", gst: "27AASFT3786G1ZG" },
  { name: "THE VEG TREAT F&B", gst: "27AAPFT2450G1Z0" },
  { name: "J S TRADERS", mobile: "9820318304", gst: "27AMZPS0455L2Z4" },
  { name: "RIDDHI SWEETS", gst: "27ACQPG0277P1ZZ" },
  { name: "THE VEG TREAT II", gst: "27AADFT9591J1ZH" },
  { name: "M/S THE VEG TREAT III", gst: "27AAKFT9631Q1Z7" },
  { name: "VEG TREAT-1", gst: "27AAOFV6019Q2Z8" },
  { name: "HOTEL RAVINDRA", gst: "27AAJFH9762K1ZO" },
  { name: "gratitude kitchen" },
  { name: "nice borivali" },
  { name: "Patel bro" },
  { name: "Murlidhar", gst: "27AARCM8016C1ZD" },
  { name: "Magnet dryfruits", mobile: "8980388187" },
  { name: "Manisha Organic" },
  { name: "Ajay Joshilkar" },
  { name: "A1 store", mobile: "7878787739", gst: "27GWEPS4031P1ZW" },
  { name: "Hishamrut", gst: "27CDOPS5353P1ZI" },
  { name: "Nice Daulat nagar" },
  { name: "Jain sweets kandarpada" },
  { name: "Zaika GSC", gst: "27AAHFV5462E1Z0" },
  { name: "Golden delicacy malad" },
  { name: "Als kitchen and grill", mobile: "9820059639" },
  { name: "BHATIA TRADERS", mobile: "9911755964", gst: "06CTMPB7915C1ZV" },
  { name: "ck son" },
  { name: "DEOKAR FARMING & PRODUCTS", mobile: "8652441263", gst: "27BJXPD4966M1Z9" },
  { name: "Vrunda Spices", gst: "27ACVPT2440A1ZJ" },
  { name: "Maruti Traders", mobile: "8957821846" },
  { name: "BBC Dahisar" },
  { name: "Cashvik foods", mobile: "8591800858" },
  { name: "PALAK TRADING CO.", mobile: "9820621201", gst: "27ADQPH1588K1ZY" },
  { name: "SU Veg" },
  { name: "Kingship Hospitality" },
  { name: "Kareems" },
  { name: "Sattva Hotel" },
  { name: "Simply Raw", gst: "09AAKCD3175A1ZT" },
  { name: "RRR MASALE", gst: "23BFCPV7096H1Z1" },
  { name: "i spice" },
  { name: "Mannyogi" },
  { name: "Krem Icecream", gst: "27BAJPB9804P1Z7" },
  { name: "Shiv shakti hotel" },
  { name: "Mahalaximi", gst: "27ERWPB5176B1ZK" },
  { name: "M M enterprise" },
  { name: "Ashwini Enterprises", gst: "27AJXPN9536C1ZL" },
  { name: "Gaurav Gupta" },
  { name: "Sir Arvind Sharma" },
  { name: "Krem Ice creams" },
  { name: "C.K & SONS", gst: "27AAKPS6672E1Z9" },
  { name: "7 Star Cafe" },
  { name: "Jyot Dairy", gst: "27AAAPG9236A1Z5" },
  { name: "Pepes Bakery" },
  { name: "Yogi nagar uncle" },
  { name: "Banajara culinary" },
  { name: "Feast" },
  { name: "Spice It Up Family Restaurant and Bar" },
  { name: "ZEST BLESSED CHOCOLATES PRIVATE LIMITED", gst: "27AAACZ7818E1Z5" },
  { name: "Miras Restaurant", gst: "27AAWFM8912H1ZN" },
  { name: "Ashapura sweets", gst: "27AMIPR8274M1Z4" },
  { name: "Sanata Pure Veg restaurant" },
  { name: "Centrepoint Dhaba" },
  { name: "Jus like that", gst: "27ABCPU6516EIZM" },
  { name: "Cash sale" },
  { name: "Samadhan Hotel Dahisar" },
  { name: "Sujay Sir" },
  { name: "Shah Traders", gst: "27AWWPS0736M1ZM" },
  { name: "Jay ambe", mobile: "9967646888" },
  { name: "Amruta agro", gst: "27HRWPK7891D1ZU" },
  { name: "Anmol agro", gst: "27ARWPK3849C1ZD" },
  { name: "Mexico\u2019s pizza cafe" },
  { name: "Karmanya" },
  { name: "Konark Veg Diet" },
  { name: "Vipul Dryfruits" },
  { name: "AURA HOTELS PVT LTD", gst: "27AAECA0153B1ZE" },
  { name: "Ambika catrers" },
  { name: "Shagun Veg Restaurant" },
  { name: "Mahalaximi Charkop" },
  { name: "More kaka" },
  { name: "Shree Hare Krishna" },
  { name: "Borivali Biryani Centre(Dahisar)", gst: "27AAACH8383C1ZL" },
  { name: "Veg sagar" },
  { name: "Golden Delicacy" },
  { name: "Sai Sarovar" },
  { name: "Times Square" },
  { name: "Banjara Thakur Village" },
  { name: "Royal masterchef" },
  { name: "Borivali Biryani Centre (chikuwadi)", gst: "27AAGFB6652B1ZP" },
  { name: "Deepak Hotel Malad" },
  { name: "Zaika Orchid Banquets & Apartment", gst: "27AAHFV5462E1Z0" },
  { name: "Zaika", gst: "27AAHFV5462E1Z0" },
  { name: "Zaika Club Aquaria", gst: "27AAHFV5462E1Z0" },
  { name: "Platess" },
  { name: "Shreeji falooda" },
  { name: "Penthouse", mobile: "9664850739" },
  { name: "Deepak hotel" },
  { name: "Bhagwati" },
  { name: "vijay" },
  { name: "vardha" },
  { name: "shiv shakti traders" },
  { name: "shree ganesh traders" },
  { name: "balaji traders" },
  { name: "Sohan bhai" },
  { name: "Shanti Ashram dryfruits" },
  { name: "Giannis" },
  { name: "Green kitchen" },
  { name: "NY cafe", mobile: "8692870276" },
];
